# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process

# Site settings
title: Human Life Alliance
logo: logo.svg
email: feedback@humanlife.org
description: Human Life Alliance promotes awareness of the inherent dignity and personhood of human life, born and preborn, without exception or compromise. Human Life Alliance proclaims and defends a culture of life and chastity through education, social and political awareness and life-affirming alternatives to abortion, infanticide, assisted suicide and euthanasia. Human Life Alliance accomplishes its mission in a spirit of prayer and non-violence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://resources.humanlife.org" # the base hostname & protocol for your site
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

twitter_username: humanlife
facebook_username: humanlifealliance
pinterest_username: humanlife1
instagram_username: humanlifealliance
youtube_username: UCIe33JnrcbSOGBzR8YYmy2Q

# Build settings
markdown: kramdown

price:
    publication: 
        amount: 0.30
        text: "$0.30"
    fact-sheet:
        amount: 0.10
        text: "$0.10"
    poster:
        amount: 1.00
        text: "$1.00"
    bumper-sticker:
        amount: 1.00
        text: "$1.00"
    other:
        amount: 0.10
        text: "$0.10"
    dvd:
        amount: 20.00
        text: "$20.00"

cart_donations_image: "donate.jpg"

payeesyform: "WSP-HUMAN-O&D0twCP5Q"
thankyoutemp: "/thank-you-temp-0451910951845610497409794"
payeesyscript: "https://script.google.com/macros/s/AKfycbyi8SArIvUBMgX-cFBwRhqa_d_Z6z2tiv9_8biz1afVaNyGCfd6/exec"